_data/authors.yml, _includes/author.html, _includes/page-author.html, _sass/_base.scss, _sass/_layout.scss, about/index.md
included a list of all authors in the footer.
closes #1
=> filled "about" page with life.

_posts/hacks/2016-11-26-getting-svn-revision-in-gradle.md, _posts/methodology/2016-11-28-is-endurance-a-good-quality-in-software-projects.md
updated the dates on the first two articles
=> updated modification dates to correct date

_includes/robots.html, _layouts/default.html, _layouts/home.html
added robots noindex on staging environment
=> no robots on staging environment

_data/navigation.yml, _includes/further_reading, _posts/2017-04-21-transparency-with-spring-boot.md, _posts/2017-05-01-monitoring-spring-boot-with-prometheus.md, _posts/2017-05-07-monitoring-error-rate-spring-boot.md, _posts/2017-07-25-configuring-localdate-serialization-spring-boot.md
so you can include a sidebar with links to posts with similar topics
=> added "further reading" sidebar

_data/navigation.yml, _posts/2019-01-28-review-java-by-comparison.md, _posts/2019-02-17-review-your-code-as-a-crime-scene.md, _posts/book-reviews/2018-08-25-review-clean-architecture.md, categories/book-reviews/index.html
=> book review "your code as a crime scene"

book/index.md
Hi,
This tiny PR will fix : 
- 1 typo in `book/index.md`
Ciao! :robot:
=> Fix typo in book/index.md

_posts/2020-06-06-spring-boot-springdoc.md
Please re-read your article a day or so after you finished writing it and work through this checklist to polish the quality. This will save all of us a lot of time during review.
**Feel free to raise the PR even if the checklist hasn't been worked through, yet**, to take advantage of the preview that is generated for each pull request (see "deploy/netlify" under "Show all checks"). But please only flag it to be reviewed after going through the checklist above.
=> Add new section "Caveats when using Code First"

_posts/2020-10-24-spring-boot-specification.md, _posts/2020-11-16-spring-data-specifications.md
Please re-read your article a day or so after you finished writing it and work through this checklist to polish the quality. This will save all of us a lot of time during review.
- [] the article has a short intro before the first headline
**Feel free to raise the PR even if the checklist hasn't been worked through, yet**, to take advantage of the preview that is generated for each pull request (see "deploy/netlify" under "Show all checks"). But please only flag it to be reviewed after going through the checklist above.
=> Adds Into to specification article

_data/authors.yml, _posts/2021-02-01-spring-boot-cookies.md
Please re-read your article a day or so after you finished writing it and work through this checklist to polish the quality. This will save all of us a lot of time during review.
**Feel free to raise the PR even if the checklist hasn't been worked through, yet**, to take advantage of the preview that is generated for each pull request (see "deploy/netlify" under "Show all checks"). But please only flag it to be reviewed after going through the checklist above.
=> cookies fixes

netlify.toml
=> add Hugo cache

content/blog/2022/2022-05-17-okhttp-retrofit.md
=> Retrofit-Updates to github code links

content/blog/2022/2022-09-01-schedule-cron-job-in-node.md, content/blog/2022/2022-09-05-schedule-cron-job-in-node.md
=> New Node-Job-Scheduler

themes/geeky/assets/scss/style.scss, themes/geeky/assets/scss/templates/_toc.scss, themes/geeky/layouts/_default/single.html
=> redesign toc

themes/geeky/layouts/authors/list.html, themes/geeky/layouts/authors/terms.html
- redesign author single page
- removed `/authors/terms.html` layout because it has no contents.
=> modified author page

themes/geeky/assets/scss/_common.scss, themes/geeky/assets/scss/templates/_main.scss, themes/geeky/layouts/_default/single.html, themes/geeky/layouts/partials/author-blurb.html
- add category as post meta instead of floating on thumbnail
- modified author style in the post footer
=> update post single page

themes/geeky/assets/scss/_common.scss, themes/geeky/assets/scss/templates/_main.scss, themes/geeky/layouts/partials/widgets/skyscraper-ad.html
- remove border and padding from the ad widget
- reduce padding on small devices
- added a little gap in the newsletter content and button
=> modified widget style

config/_default/params.toml
- Update copyright links to the original author
=> update copyright links

themes/geeky/assets/scss/_buttons.scss, themes/geeky/assets/scss/templates/_main.scss, themes/geeky/layouts/_default/post.html, themes/geeky/layouts/index.html, themes/geeky/layouts/partials/list.html
- Improved padding issue
- Added author avatar
- Improved button
=> improved blog card

config/_default/params.toml, themes/geeky/assets/plugins/search/search.js, themes/geeky/assets/scss/_reflectoring.scss, themes/geeky/assets/scss/bootstrap/_offcanvas.scss, themes/geeky/assets/scss/bootstrap/_variables.scss, themes/geeky/assets/scss/templates/_navigation.scss, themes/geeky/layouts/partials/header.html, themes/geeky/layouts/partials/logo.html
- Improved look and feel
- fixed responsive broken menu
- update the search component, now it will automatically focus when the search is open
- enlarged social icon for better UX
=> improved header component

content/blog/2023/2023-01-06-building-csv-importer-with-nodejs.md
=> CSV importer

content/blog/2023/2023-01-25-junit5-parameterized-tests.md, data/authors.yml
=> Parameterized tests with JUnit 5 - minor corrections

content/blog/2023/2023-09-25-introduction-to-kotest.md, content/blog/2023/2023-10-14-introduction-to-kotest.md
=> intro to Kotest
